### ISSUE TITLE
Waiting for your friend kısmında takılması

### ISSUE THREAD

**Issue by furkanalptokac** [bilalucar/tic-tac-toe#2]
Test etmek için arkadaşımla oynuyorduk, birkaç oyun sonra berabere bittikten sonra replay dediğimizde ikimizde de "Waiting for your friend" kısmında kaldı. Denemek için hamle yapmayı denedim, 1 kez O koyduktan sonra başka hamleye izin vermedi. Ayrıca arkadaşım bu hamleyi görebildi, fakat o oynayamıyor.

**Comment by bilalucar** [comment]
En kısa sürede testlerini yapıp hatayi düzelteceğim. Hatayı bildirdiğiniz için teşekkürler 👍
